services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: playlistsnow-backend
    container_name: playlistsnow-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_USER_FILE=/run/secrets/db_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_CLUSTER=playlistsnow.meiecfs.mongodb.net
      - DB_NAME=playlistsnow
    secrets:
      - db_user
      - db_password
    networks:
      - playlistsnow-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: playlistsnow-frontend
    container_name: playlistsnow-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    networks:
      - playlistsnow-network
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

networks:
  playlistsnow-network:
    driver: bridge
    name: playlistsnow-network

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
