services:

  # mongo-db:
  #   image: mongo:6.0.6
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mern_user
  #     MONGO_INITDB_ROOT_PASSWORD: israelFovLoVert
  #   volumes:
  #     - ./DevOps-Proyect-Bakend/mongo:/data/db
  #   ports:
  #     - "27017:27017"
  #   healthcheck:
  #     test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "8080:8080"
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3000:80"
    restart: unless-stopped