services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: playlistsnow-backend
    container_name: playlistsnow-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb+srv://playlistsnow:playlistsnow@playlistsnow.meiecfs.mongodb.net/playlistsnow?retryWrites=true&w=majority
    networks:
      - playlistsnow-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: playlistsnow-frontend
    container_name: playlistsnow-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    networks:
      - playlistsnow-network
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

networks:
  playlistsnow-network:
    driver: bridge
    name: playlistsnow-network
