apiVersion: v1
kind: Service
metadata:
  name: web-hello-svc
  namespace: upc-devops
  labels:
    app: web-hello
spec:
  type: ClusterIP
  selector:
    app: web-hello
  ports:
    - name: backend
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: frontend
      port: 80
      targetPort: 80
      protocol: TCP
